### ISSUE TITLE
[PATCH] After the removal of cwd from @INC t/setup_common is not found.

### ISSUE THREAD

**Issue by gregoa** [briandfoy/test-file#14]
In Debian we are currently applying the following patch to Test-File.
We thought you might be interested in it too.

    Description: After the removal of cwd from @INC t/setup_common is not found.
     Change the requires in the tests to use ./t/setup_common.
    Origin: vendor
    Bug-Debian: https://bugs.debian.org/837237
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-09-10
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest-file-perl.git/plain/debian/patches/t_setup_common_require_cwd.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by briandfoy** [comment]
A pull request would work nicely :)

**Comment by gregoa** [comment]
I just noticed that you were faster and already commited the change in 4da2d9c - thank you!
I guess this issue can be closed now.

**Comment by briandfoy** [comment]
Thanks of the work either way! As long as it gets fixed!
