### ISSUE TITLE
can not install using CPANPLUS 0.9160, perl 5.10.1

### ISSUE THREAD

**Issue by martinthurn-LFT** [briandfoy/test-file#15]
Installing Test::File (1.442)
[MSG] Using cached file '/home/martin/.cpanplus/authors/id/B/BD/BDFOY/CHECKSUMS' on disk; ttl (3600s) is not exceeded
[MSG] Checksum matches for 'Test-File-1.442.tar.gz'
[MSG] Extracting 'Test-File-1.442.tar.gz'
[MSG] Extracted 'Test::File' to '/home/martin/.cpanplus/5.10.1/build/aoDF6d2Ga3/Test-File-1.442'
==> MISSING Signature file! <==
Running [/usr/bin/perl -e use strict; BEGIN { my $old = select STDERR; $|++; select $old; $|++; $0 = shift(@ARGV); my $rv = do($0); die $@ if $@; } /home/martin/.cpanplus/5.10.1/build/aoDF6d2Ga3/Test-File-1.442/Makefile.PL]...
Use of uninitialized value $makestat in numeric lt (<) at /usr/share/perl5/CPANPLUS/Dist/MM.pm line 413.
Use of uninitialized value $makestat in subtraction (-) at /usr/share/perl5/CPANPLUS/Dist/MM.pm line 414.
[ERROR] File '/home/martin/.cpanplus/5.10.1/build/aoDF6d2Ga3/Test-File-1.442/Makefile' is not readable or does not exist

Key 'file' (/home/martin/.cpanplus/5.10.1/build/aoDF6d2Ga3/Test-File-1.442/Makefile) is of invalid type for 'CPANPLUS::Dist::MM::_find_prereqs' provided by CPANPLUS::Dist::MM::prepare at /usr/share/perl5/CPANPLUS/Module.pm line 823.
[ERROR] Unable to scan '/home/martin/.cpanplus/5.10.1/build/aoDF6d2Ga3/Test-File-1.442/Makefile' for prereqs

[ERROR] Unable to create a new distribution object for 'Test::File' -- cannot continue

**Comment by briandfoy** [comment]
Noted, but my first suspicion is that this is a problem with CPANPLUS. Can you run the Makefile.PL manually?

**Comment by martinthurn-LFT** [comment]
Hmm, yes, manual installation steps run smoothly and easily.

**Comment by briandfoy** [comment]
I was able to reproduce this on perl5.10.1 and CPANPLUS 0.9160. I've also been able to make it work by getting rid of that nonsense with

`use strict; BEGIN { my $old = select STDERR; $|++; select $old; $|++; $0 = shift(@ARGV); my $rv = do($0); die $@ if $@; } `

**Comment by martinthurn-LFT** [comment]
Fair enough.  Thank you so much for the explanation!
