### ISSUE TITLE
Test::Manifest changes which tests run

### ISSUE THREAD

**Issue by haarg** [briandfoy/test-file#16]
Depending on if Test::Manifest is installed, different tests will be run.  With Test::Manifest, t/rt/30346.t will run because it is mentioned in t/test_manifest.  Without Test::Manifest it will not run because EUMM does not run tests in subdirectories of t/ by default.  Test::Manifest will prevent t/file_contains_utf8.t from running because it is not mentioned in the manifest.

**Comment by briandfoy** [comment]
The Makefile.PL now specifies that it should test in subdirs: d08b1518028a378f5b35894fda6a48bd91882968

I've updated _t/test_manifest_ with the missing tests: 1419bd9ebea041e9fe64178c1bf6e1c58bd3bb52

Thanks!
