### ISSUE TITLE
Tests fail on some cygwin systems

### ISSUE THREAD

**Issue by eserte** [briandfoy/test-file#17]
On some cygwin installations the test suite fails. Here's a fail report at CPAN Testers: http://www.cpantesters.org/cpan/report/05b8e62e-a914-1014-a63b-77b394f39f87

I stumbled over the problem while running tests on appveyor using cygwin's perl:
https://ci.appveyor.com/project/eserte/slay-makefile/build/1.0.16#L1099

A guess: it seems that some (or all?) of the failing tests are about unreadable files. These are skipped if uid==0. Windows (and cygwin) systems behave different for unreadable files. It's probably just luck that `$<` is always zero on Windows, and maybe most of the time also zero on cygwin systems, but not always, and so these tests are skipped on most installations.

**Comment by briandfoy** [comment]
Thanks for this report, and I'll eventually get to it.

**Comment by briandfoy** [comment]
At least I have Appveyor testing on cygwin Perl now.

**Comment by briandfoy** [comment]
I think I have this working now. I've pushed 1.445 to CPAN.
