### ISSUE TITLE
Don't allow plain file tests to run on non-plain files

### ISSUE THREAD

**Issue by chanwilson** [briandfoy/test-file#18]
Imagine my surprise when `file_not_empty_ok()` and friends return ok on a directory:
```
% perl -MTest::File -e 'file_not_empty_ok("/etc")'
ok 1 - /etc is not empty
# Tests were run but no plan was declared and done_testing() was not seen.
```
A perusal of `File.pm` does indeed show it doesn't actually test to make sure the file tests are actually against .... files.

**Comment by barefootcoder** [comment]
> A perusal of File.pm does indeed show it doesn't actually test to make sure the file tests are actually against .... files.

Well, if you come from a Unix background, you're used to the philosophy of "everything is a file": a device is a file, a socket is a file, a symlink is a flle, and, ultimately, a directory is a file too.  In later versions of Unixoid systems, directories have diverged from files more significantly, but I'm old enough to remember when you could actually `cat` a directory. ;->  Of course, in Windows-world, a file and a directory were always completely different animals.

Now, all that having been said:  While I don't think it's necessarily a good thing _in general_ for file tests to refuse to work on directories, I do agree that this particular one could be a surprising result.  Even more suprising is that, as far as this test is concerned, a directory is _never_ empty: if you run it on a newly created directory, it still says "ok."  I suppose that even a fresh directory contains `.` and `..`, so in that sense it's not empty, but it still feels a bit wonky.

But, then, what _should_ it do?  Should a directory fail _both_ the `file_empty_ok` test and the `file_not_empty_ok` test (sort of like a `NULL` in SQL)?  Should it perhaps throw some sort of "don't use file tests on a directory" exception?  I'm not entirely sure.

Ultimately this has to be brian d foy's call.  I just wanted to weigh in and point out that the answers are not as obvious as one might think. ;->

**Comment by briandfoy** [comment]
I've added a test diagnostic message to each of the functions where a directory might be inappropriate. This gives me some time to warn people that these functions might later disallow these things.

**Comment by briandfoy** [comment]
I've been thinking a lot about this one, and I'm going to deprecate directories as arguments for these. This basically punts the problem to the future. I'll see what turns up if people get these deprecation messages.

**Comment by briandfoy** [comment]
So this is now in v1.991 and I'll see who complains. There have been warnings for a couple years and I haven't heard anyone complain, so we might be good.

If there are more problems, someone can respond to this issue to re-open it, or start a new issue.
