### ISSUE TITLE
Mismatching license

### ISSUE THREAD

**Issue by ppisar** [briandfoy/test-file#21]
LICENSE  reads:

~~~~
The Test::File module is licensed under the same terms as perl
itself, under the Artistic License 2.0.
~~~~

That paragraph contradicts itself because Perl is not licensed under "Artistic License 2.0" but under "GPL version 1 or later, or Artistic 1 license" <https://dev.perl.org/licenses/>. The "Artistic License" link on the Perl web page points to <https://dev.perl.org/licenses/artistic.html>. That's a different license than the LICENSE file quotes underneath.

Could please correct the LICENSE text so that it does not mention Artistic 2.0 license as this is what you (or whoever wrote it) probably mean?

**Comment by briandfoy** [comment]
I've clarified that this is Artistic License 2.0 in 2f4ec8a084969fa24dc1393933c21dd6f06261b7. Thanks for spotting that.
