### ISSUE TITLE
Documentation mentions non-existent package Test2::Tool::File

### ISSUE THREAD

**Issue by exodist** [briandfoy/test-file#25]
The docs for Test::File link to Test2::Tool::File, which does not exist. I suspect this was supposed to be Test2::Tool[s]::File, but that package also does not appear to exist.

**Comment by exodist** [comment]
Looks like I was correct about the typo (missing 's') but the correct package only exists on github (https://github.com/torbjorn/Test2-Tools-File) not on cpan/metacpan.

**Comment by briandfoy** [comment]
Fixed in 88e4e4e5b3645d3ba586ebafcf8cae9e42b4641c. Thanks,
