### ISSUE TITLE
Test::File does not account for user names that are only numbers

### ISSUE THREAD

**Issue by hhg7** [briandfoy/test-file#26]
https://stackoverflow.com/questions/66426472/cannot-install-testfile-on-perl-5-32-0-macos-sierra/66427502#66427502

I'm attempting to install `DateTime` on my perlbrew 5.32.0, but the tests for its dependency `Test::File` are failing. The important part is as follows:

    t/owner.t ..................... # File [blib] belongs to 703404669 (729761796), not 703404669 (703404669)!
    t/owner.t ..................... 1/? 
    #   Failed test 'owner_is with text username'
    #   at t/owner.t line 99.
    
    #   Failed test 'Intentional owner_isnt failure'
    #   at t/owner.t line 146.
    # STDOUT is:
    # > ok 1 - blib doesn't belong to 703404669
    # not:
    # > not ok 1 - blib doesn't belong to 703404669
    # as expected
    # STDERR is:
    # > 
    # > 
    # > 
    # not:
    # > # File [blib] belongs to 703404669 (729761796)!
    # > #   Failed test 'blib doesn't belong to 703404669'
    # > #   at t/owner.t line 145.

I got similar errors earlier, but  almost every package within my `~/.cpan` directory has a `blib` so I'm not sure which directory cpan is talking about.

My OS is MacOS Sierra 10.12.6 (16G2136)

this error was resolved by Schwern:

The problem is your user name is a number and Test::File does not seem to account for that.

owner_is checks if a file is owned by the given user. It accepts a user name or numeric user ID. If its given a number it assumes it's a numeric ID. If 703404669 is your username it will get confused and use that as a user id. Your user id is really 729761796. 703404669 != 729761796.

Test::File can guard against this ambiguity by verifying with getpwuid and/or checking getpwnam first.

**Comment by briandfoy** [comment]
I don't think this is completely fixable, but maybe someone can show we the way. This is all concentrated in the `_get_uid` and `_get_gid` functions. But, I cannot create all numeric user ids on either macOS or Ubuntu. How did you do that (and curious, why?)

I think the best option for you is the force install Test::File.

**Comment by briandfoy** [comment]
Test::File 1.447_01 is on its way to CPAN Testers.

**Comment by hhg7** [comment]
@briandfoy I did not choose the all-numeric username, and am unable to change it.

**Comment by briandfoy** [comment]
Let me know how 1.448 works out for you.

**Comment by hhg7** [comment]
Thank you! My install on perl 5.32.1 with Mac OS Darwin 16.7.0 installed without any problem
